# Generated by Django 3.1.7 on 2021-06-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0031_auto_20210601_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control_usuarios',
            name='nombre_usuario',
        ),
    ]
